spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dubbo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 10000
  cache:
    redis:
      time-to-live: 360000000
    type: redis


server:
  servlet:
    context-path: /manager
  port: 8020


#dubbo≈‰÷√
dubbo:
  application:
    name: admin-service
  registry:
    address: zookeeper://119.23.187.31:2181
  scan:
    base-packages: com.ouyang.admin
  monitor:
    protocol: registry
